[package]
name = "wasm_bindgen_duck_type"
author = "Graic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm_bindgen_duck_type_macro_impl = { path = "wasm_bindgen_duck_type_macro_impl" }
